# PyTorch Tensors

- This tutorial briefly describes some basic operations on Tensors in PyTorch. 
- This [documentation](http://pytorch.org/docs/master/torch.html) from pytorch contains information about all the possible operations on Tensors.

In [1]:
import torch
import torch.nn as nn
import numpy as np

## Getting started with Tensors

### Creating a Tensor

In [2]:
#Create Torch Tensor from a list
x = torch.Tensor([[1,2,3],[4,5,6]])
print (x) # prints the tensor
print ('shape: ',x.shape) # returns the shape of the tensor. You can also use x.size()


 1  2  3
 4  5  6
[torch.FloatTensor of size 2x3]

shape:  torch.Size([2, 3])


- you can use the `.numpy()` function to obtain the numpy array from tensor.

In [3]:
print ('numpy array: ')
print (x.numpy()) # obtains the numpy array from the pytorch Tensor

numpy array: 
[[1. 2. 3.]
 [4. 5. 6.]]


- The default `torch.Tensor` is a float tensor as you can see above.
- You can use `torch.LongTensor` for tensor of integer types.

In [4]:
x = torch.LongTensor([1,4,6])
print (x) # prints the tensor
print ('shape: ', x.shape) # returns the shape of the tensor. You can also use x.size()
print ('numpy array: ',x.numpy()) #obtains the numpy array


 1
 4
 6
[torch.LongTensor of size 3]

shape:  torch.Size([3])
numpy array:  [1 4 6]


- You can also create Tensors from numpy arrays

In [5]:
one_arr = np.ones(5) # a numpy array
print (one_arr)

[1. 1. 1. 1. 1.]


In [6]:
x = torch.from_numpy(one_arr)
print (x) 
print (x.shape) #obtains the shape of the tensor


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

torch.Size([5])


In [7]:
print (x.numpy()) #obtains the numpy array from the Tensor

[1. 1. 1. 1. 1.]


### Indexing into a Tensor

In [8]:
a = np.random.rand(3,4,5)
x = torch.from_numpy(a)
print (x)
print ('shape: ',x.shape)


(0 ,.,.) = 
  0.6733  0.8095  0.4826  0.7762  0.2518
  0.7623  0.6694  0.1983  0.4339  0.9340
  0.9950  0.1091  0.3859  0.2677  0.8724
  0.6042  0.6788  0.4640  0.4108  0.9463

(1 ,.,.) = 
  0.4434  0.7593  0.8383  0.9634  0.5537
  0.9513  0.4264  0.6092  0.0246  0.4474
  0.1747  0.3231  0.7231  0.7409  0.8272
  0.2956  0.0210  0.2378  0.5568  0.9036

(2 ,.,.) = 
  0.5021  0.8497  0.0324  0.3825  0.0973
  0.3613  0.3155  0.5155  0.8660  0.9879
  0.9271  0.9339  0.0655  0.0728  0.1948
  0.7918  0.1789  0.7803  0.3370  0.0860
[torch.DoubleTensor of size 3x4x5]

shape:  torch.Size([3, 4, 5])


In [9]:
# you can index into them like arrays
print (x[0]) #gives you a matrix Tensor
print (x[0].shape)


 0.6733  0.8095  0.4826  0.7762  0.2518
 0.7623  0.6694  0.1983  0.4339  0.9340
 0.9950  0.1091  0.3859  0.2677  0.8724
 0.6042  0.6788  0.4640  0.4108  0.9463
[torch.DoubleTensor of size 4x5]

torch.Size([4, 5])


In [10]:
# you can index into them like arrays
print (x[0][2]) # gives you a vector Tensor
print (x[0][2].shape)


 0.9950
 0.1091
 0.3859
 0.2677
 0.8724
[torch.DoubleTensor of size 5]

torch.Size([5])


In [11]:
print (x[0][2][3]) #this gives you a scalar

0.2677072749253966


### Reshaping a Tensor

- To reshape a tensor to a different size, you can use the `.view()` function. 
- The `.view()` function returns a tensor with the same data as the self tensor but of a different size

In [12]:
a = np.random.rand(2,6)
x = torch.from_numpy(a)
print (x)
print ('shape: ',x.shape)


 0.0220  0.7731  0.4344  0.9481  0.6275  0.0657
 0.3953  0.3793  0.1728  0.3105  0.4176  0.0763
[torch.DoubleTensor of size 2x6]

shape:  torch.Size([2, 6])


In [13]:
y = x.view(3,4) #reshapes it into a tensor of size 3 x 4
print (y)
print (y.shape)


 0.0220  0.7731  0.4344  0.9481
 0.6275  0.0657  0.3953  0.3793
 0.1728  0.3105  0.4176  0.0763
[torch.DoubleTensor of size 3x4]

torch.Size([3, 4])


In [14]:
y = x.view(2,3,2) #reshapes the tensor into 2 x 3 x 2
print (y)
print (y.shape)


(0 ,.,.) = 
  0.0220  0.7731
  0.4344  0.9481
  0.6275  0.0657

(1 ,.,.) = 
  0.3953  0.3793
  0.1728  0.3105
  0.4176  0.0763
[torch.DoubleTensor of size 2x3x2]

torch.Size([2, 3, 2])


- if one of the dimensions is `-1`, as shown below, then its size can be inferred. So, you cannot have multiple -1's in view.

In [15]:
y = x.view(4,3) #reshapes the tensor into 4x3
print (y)
print (y.shape)


 0.0220  0.7731  0.4344
 0.9481  0.6275  0.0657
 0.3953  0.3793  0.1728
 0.3105  0.4176  0.0763
[torch.DoubleTensor of size 4x3]

torch.Size([4, 3])


In [16]:
y = x.view(4,-1) #same as above, but the second dimension can be inferred.
print (y)
print (y.shape)


 0.0220  0.7731  0.4344
 0.9481  0.6275  0.0657
 0.3953  0.3793  0.1728
 0.3105  0.4176  0.0763
[torch.DoubleTensor of size 4x3]

torch.Size([4, 3])


### Operations on Tensors

- You can do some basic operations on tensors like arrays

In [17]:
a = np.random.rand(1,5)
x = torch.from_numpy(a)
print (x)
print (x.shape)


 0.8764  0.7787  0.3406  0.0979  0.2234
[torch.DoubleTensor of size 1x5]

torch.Size([1, 5])


In [18]:
b = np.ones((1,5))
y = torch.from_numpy(b)
print (y)
print (y.shape)


 1  1  1  1  1
[torch.DoubleTensor of size 1x5]

torch.Size([1, 5])


In [19]:
print (x + y) #element wise addition


 1.8764  1.7787  1.3406  1.0979  1.2234
[torch.DoubleTensor of size 1x5]



In [20]:
print (x - y) #element wise subtraction


-0.1236 -0.2213 -0.6594 -0.9021 -0.7766
[torch.DoubleTensor of size 1x5]



In [21]:
print (x * y)  #element wise multiplication


 0.8764  0.7787  0.3406  0.0979  0.2234
[torch.DoubleTensor of size 1x5]



- Another useful operation on tensors is concatenation.
- You can use the `torch.cat()` function, it takes in a list/sequence of tensors and concatenates them

In [22]:
torch.cat([x,y]) # concatenates them along the row (dim=0) by default.


 0.8764  0.7787  0.3406  0.0979  0.2234
 1.0000  1.0000  1.0000  1.0000  1.0000
[torch.DoubleTensor of size 2x5]

In [23]:
torch.cat([x,y], dim=1) # concatenates them along the column when dim=1 is mentioned.


 0.8764  0.7787  0.3406  0.0979  0.2234  1.0000  1.0000  1.0000  1.0000  1.0000
[torch.DoubleTensor of size 1x10]

- If you want to expand a Tensor along the singleton dimension, you can use the `.expand()` function.

In [24]:
x = torch.Tensor([[1],[2],[3]])
print (x)
print (x.shape)


 1
 2
 3
[torch.FloatTensor of size 3x1]

torch.Size([3, 1])


In [25]:
x.expand(3,4) #expands it along the second dimension from (3 x 1) to be (3 x 4)


 1  1  1  1
 2  2  2  2
 3  3  3  3
[torch.FloatTensor of size 3x4]

In [26]:
x = torch.Tensor([5,6]).view(-1,2) #reshaping it to 1 x 2
x.expand(5,2) #expands it along the first dimension from (1 x 2) to (5 x 2)


 5  6
 5  6
 5  6
 5  6
 5  6
[torch.FloatTensor of size 5x2]

- These are the basic operations on the Tensors that will be very useful. You can check the [documentation here](http://pytorch.org/docs/master/torch.html) for all list of operations.